import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const poppins = Poppins({ subsets: ["latin"], weight: ['100', '200', '300', "400", "500",  '600',"700", '800', '900'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={poppins.className}>
        <main className="mx-auto">
          <Header />
          {children}
          <footer className="border-t p-1 text-xs text-center text-gray-500">
            &copy; 2024 All rights reserved
          </footer>
        </main>
      </body>
    </html>
  );
}
